# Generated by Django 5.2.4 on 2025-07-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dropoff_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='cost_ammount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
    ]
